image:
  repository: tccr.io/truecharts/whoami
  pullPolicy: IfNotPresent
  tag: 1.8.7@sha256:8c61f0ca92fd806fcb4ed1465cb793c05443f37951554b105b0f2dc686a95772

service:
  main:
    ports:
      main:
        port: 8080

args:
  - --port
  - '8080'

manifests:
  enabled: false
  staging: false

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true

# addons:
#   codeserver:
#     enabled: true
#     service:
#       type: LoadBalancer
#       ports:
#         codeserver:
#           nodePort: 30067
