image:
  repository: tccr.io/truecharts/whoami
  pullPolicy: IfNotPresent
  tag: 1.8.7@sha256:8c61f0ca92fd806fcb4ed1465cb793c05443f37951554b105b0f2dc686a95772

workload:
  main:
    enabled: true
    primary: true
    type: DaemonSet
    podSpec: {}

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

args:
  - --port
  - "8080"

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true
