image:
  repository: tccr.io/truecharts/whoami
  pullPolicy: IfNotPresent
  tag: 1.8.7@sha256:8c61f0ca92fd806fcb4ed1465cb793c05443f37951554b105b0f2dc686a95772

workload:
  main:
    pod:
      containers:
        main:
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
  job:
    enabled: true
    type: Job
    podSpec:
      restartPolicy: Never
      containers:
        main:
          args:
            - --port
            - "8081"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
  job:
    enabled: true
    type: CronJob
    schedule: "* * * * *"
    podSpec:
      restartPolicy: OnFailure
      containers:
        main:
          args:
            - --port
            - "8082"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080
