image:
  repository: tccr.io/truecharts/whoami
  pullPolicy: IfNotPresent
  tag: 1.8.7@sha256:8c61f0ca92fd806fcb4ed1465cb793c05443f37951554b105b0f2dc686a95772

service:
  main:
    ports:
      main:
        port: 8080

workload:
  main:
    pod:
      containers:
        main:
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

manifests:
  enabled: false
  staging: false


networkPolicy:
  main:
    enabled: true

    ingress:
    - from:
      - ipBlock:
          cidr: 172.17.0.0/16
          except:
          - 172.17.1.0/24
      - namespaceSelector:
          matchLabels:
            project: myproject
      - podSelector:
          matchLabels:
            role: frontend
      - namespaceSelector:
          matchLabels:
            project: myproject2
        podSelector:
          matchLabels:
            role: frontend2
      ports:
      - protocol: TCP
        port: 6379
    egress:
    - to:
      - ipBlock:
          cidr: 172.17.2.0/16
          except:
          - 172.17.2.0/24
      - namespaceSelector:
          matchLabels:
            project: myproject3
      - podSelector:
          matchLabels:
            role: frontend3
      - namespaceSelector:
          matchLabels:
            project: myproject4
        podSelector:
          matchLabels:
            role: frontend4
      ports:
      - protocol: TCP
        port: 5978
