apiVersion: v2
appVersion: ""
dependencies:
- name: common
  repository: file://../common
  version: ~13.2.0
deprecated: false
description: Helper chart to test different use cases of the common library
home: https://github.com/truecharts/apps/tree/master/charts/library/common-test
icon: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
keywords:
- common-test
- truecharts
- common
- test
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: common-test
sources:
- https://github.com/truecharts/apps/tree/master/charts/library/common-test
type: application
version: 1.0.0
