workload:
  main:
    type: CronJob
    enabled: true
    schedule: "*/1 * * * *"
    podSpec:
      containers:
        main:
          enabled: true

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 80

manifestManager:
  enabled: false
  staging: false
