workload:
  main:
    enabled: true
    podSpec:
      containers:
        main:
          enabled: true

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 80

manifests:
  enabed: false
  staging: false
