workload:
  main:
    enabled: true
    podSpec:
      containers:
        main:
          enabled: false

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 80
