---
apiVersion: v1
kind: Namespace
metadata:
  name: tc-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: force-manifests
  namespace: tc-system
spec:
  template:
    spec:
      serviceAccountName: force-manifests
      containers:
        - name: force-manifests
          image: tccr.io/truecharts/ubuntu:jammy-20221101@sha256:4b9475e08c5180d4e7417dc6a18a26dcce7691e4311e5353dbb952645c5ff43f
          command:
            - "/bin/sh"
            - "-c"
            - |
              /bin/bash <<'EOF'
              echo "installing manifests..."
              kubectl apply --server-side --force-conflicts  -k https://github.com/truecharts/manifests/ || echo "Manifest application failed..."
              EOF
      restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: force-manifests
  namespace: tc-system
rules:
  - apiGroups:  ["*"]
    resources:  ["*"]
    verbs:  ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: force-manifests
  namespace: tc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: force-manifests
subjects:
  - kind: ServiceAccount
    name: force-manifests
    namespace: tc-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: force-manifests
  namespace: tc-system
