image:
  repository: ghcr.io/truecharts/whoami
  pullPolicy: IfNotPresent
  tag: v1.8.1@sha256:7df92e7d31662558dbadb11dd532a225a6b0bfd14fe22747b0b589062375a1f5

service:
  main:
    ports:
      main:
        port: 8080
