# TODO: Docs
# Defines image info
image:
  repository: repo
  tag: tag
  pullPolicy: IfNotPresent

openvpnImage:
  repository: tccr.io/truecharts/openvpn-client
  tag: latest@sha256:1f83decdf614cbf48e2429921b6f0efa0e825f447f5c510b65bc90f660227688
  pullPolicy: IfNotPresent

wireguardImage:
  repository: tccr.io/truecharts/wireguard
  tag: v1.0.20210914@sha256:9f56e5660e8df8d4d38521ed73a4cc29fa24bf578007bfbe633e00184e2ebfbc
  pullPolicy: IfNotPresent

tailscaleImage:
  repository: tailscale/tailscale
  # TODO: Switch to stable once a v1.33.x is released
  tag: v1.34.1@sha256:69bec9fdea25765e1b9dd129ccaeaf1e160f1132bb390535772fa939f0bf620b
  pullPolicy: IfNotPresent

codeserverImage:
  repository: tccr.io/truecharts/code-server
  tag: 4.9.1@sha256:b339bd8f6da4c73c0259d6951991278aa1595a6be570a207ce635c75aac9893d
  pullPolicy: IfNotPresent

alpineImage:
  repository: tccr.io/truecharts/alpine
  tag: v3.17.0@sha256:f8607e14a5e456c1b8fe50b7f0c9371b4aae543d23080f5e2fe0bdbb06d2413b
  pullPolicy: IfNotPresent

scratchImage:
  repository: tccr.io/truecharts/scratch
  tag: latest@sha256:b4289ea433ec1308f6f2e8bff3f23bcd52b751ccb691284210ed826385ba9317
  pullPolicy: IfNotPresent

kubectlImage:
  repository: tccr.io/truecharts/kubectl
  tag: v1.26.0@sha256:e56d1c8dd3ba85bb8410cc9f5c04f03f814e4b76ffcc7f12730868faba5b9c52
  pullPolicy: IfNotPresent

wgetImage:
  repository: tccr.io/truecharts/wget
  tag: v0.0.1
  pullPolicy: IfNotPresent

postgresClientImage:
  repository: tccr.io/truecharts/db-wait-postgres
  tag: v0.0.1
  pullPolicy: IfNotPresent

mariadbClientImage:
  repository: tccr.io/truecharts/db-wait-mariadb
  tag: v0.0.1
  pullPolicy: IfNotPresent

redisClientImage:
  repository: tccr.io/truecharts/db-wait-redis
  tag: v0.0.1
  pullPolicy: IfNotPresent

mongodbClientImage:
  repository: tccr.io/truecharts/db-wait-mongodb
  tag: v0.0.1
  pullPolicy: IfNotPresent
# -- Global values
global:
  # -- Set additional global labels
  labels: {}
  # -- Set additional global annotations
  annotations: {}
  # -- Adds metalLB annotations to services
  addMetalLBAnnotations: false
  # -- Adds traefik annotations to services
  addTraefikAnnotations: false
  # -- Minimum nodePort value
  minNodePort: 9000

# TODO: Docs
fallbackDefaults:
  # -- Define a storageClassName that will be used for all PVCs
  # Can be overruled per PVC
  storageClass:
  # -- Default Service Protocol
  serviceProtocol: TCP
  # -- Default Service Type
  serviceType: ClusterIP
  # -- Default persistence type
  persistenceType: pvc
  # -- Default Retain PVC
  pvcRetain: false
  # -- Default PVC Size
  pvcSize: 1Gi
  # -- Default PVC Access Modes
  pvcAccessModes:
    - ReadWriteOnce

# TODO: Docs (for the imageName) convention
# -- Image values
image:
  # -- Image repository
  repository: traefik/whoami
  # -- Image tag
  tag: latest
  # -- Image pull policy
  pullPolicy: IfNotPresent

# TODO: Docs
# -- Security Context
securityContext:
  # -- Container security context for all containers
  # Can be overruled per container
  container:
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      add: []
      drop:
        - ALL
  # -- Pod security context for all pods
  # Can be overruled per pod
  pod:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: []
    sysctls: []

# TODO: Docs
containerOptions:
  # -- Resources
  # Can be overruled per container
  resources:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 10m
      memory: 50Mi
  # -- PUID for all containers
  # Can be overruled per container
  PUID: 568
  # -- UMASK for all containers
  # Can be overruled per container
  UMASK: "002"
  NVIDIA_CAPS:
    - all

# -- Options for all pods # TODO: Docs
# Can be overruled per pod
podOptions:
  enableServiceLinks: false
  hostNetwork: false
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  dnsConfig:
    options:
      - name: ndots
        value: "2"
  hostAliases: []
  nodeSelector: {}
  tolerations: []
  schedulerName: ""
  priorityClassName: ""
  runtimeClassName: ""
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 120

# -- (docs/workload/README.md)
workload:
  main:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      # TODO: Currently implementing
      containers:
        main:
          enabled: true
          primary: true
          imageSelector: image
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              add: []
              drop:
                - ALL
          env: {}
          envList: []
          envFrom: []
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          probes:
            liveness:
              enabled: true
              type: HTTP
              port:
              path:
              httpHeaders: {}
              command: []
            readiness:
              enabled: true
              type: HTTP
              port:
              path:
              httpHeaders: {}
              command: []
            startup:
              enabled: true
              type: HTTP
              port:
              path:
              httpHeaders: {}
              command: []
      initContainers:
        init-cont-name:
          enabled: false
          type: install
          # ...containerSpec
# TODO:
portal: {}

# -- VolumeClaimTemplates (StatefulSet only)
volumeClaimTemplates:
  # -- VolumeClaimTemplate name
  vct-name:
    # -- Enables the VolumeClaimTemplate
    enabled: true
    # -- VolumeClaimTemplate labels
    labels: {}
    # -- VolumeClaimTemplate annotations
    annotations: {}
    # -- VolumeClaimTemplate access modes
    accessModes:
      - ReadWriteOnce
    # -- VolumeClaimTemplate storage class
    storageClassName: ""
    # -- VolumeClaimTemplate size
    size: 1Gi
    # -- Options that apply to all volumeMounts
    # Can be overruled per volumeMount under targetSelector
    # -- VolumeClaimTemplate mount path
    mountPath: /data
    readOnly: false
    subPath: ""
    mountPropagation: ""
    # targetSelector:
    #   pod-name:
    #     container-name:
    #       mountPath: /data
    #       readOnly: false
    #       subPath: ""
    #       mountPropagation: ""

# -- SCALE GPU (TODO: Only the resources part is left)
scaleGPU:
  - gpu:
      key: value
    # Without targetSelector, the gpu will
    # be applied to primary pod/container
    targetSelector:
      pod-name:
        - container-name

##### ⬇ Done ⬇ #####

# -- (docs/persistence/README.md)
persistence:
  shared:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /shared
    targetSelectAll: true
  varlogs:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /var/logs
    targetSelectAll: true
  tmp:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /tmp
    targetSelectAll: true
  devshm:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /dev/shm
    targetSelectAll: true

# -- (docs/service/README.md)
service:
  main:
    enabled: true
    primary: true
    ports:
      main:
        enabled: true
        primary: true
        protocol: HTTP

# -- Timezone used everywhere applicable
TIMEZONE: UTC

# -- Injected from SCALE middleware
# Only for reference here
ixExternalInterfacesConfiguration: []
# -- Injected from SCALE middleware
# Only for reference here
ixExternalInterfacesConfigurationNames: []
# -- Injected from SCALE middleware
# Only for reference here
ixCertificates: []
# -- Injected from SCALE middleware
# Only for reference here
ixVolumes: []

# -- (docs/imagePullSecrets.md)
imagePullSecret: []

# -- (docs/configmap.md)
configmap: {}

# -- (docs/secret.md)
secret: {}

# -- (docs/serviceAccount.md)
serviceAccount: {}

# -- (docs/rbac.md)
rbac: {}

# -- (docs/scaleExternalInterface.md)
scaleExternalInterface: []

# -- (docs/scaleCertificate.md)
scaleCertificate: {}

# NOTES.txt TODO: Docs
notes:
  header: |
    # Welcome to SCALE
    Thank you for installing <{{ .Chart.Name }}>.
  # custom: "{{ toYaml $.Values }}"
  custom: ""
  footer: |
    # Documentation
    Documentation for this chart can be found at ...
    # Bug reports
    If you find a bug in this chart, please file an issue at ...
