# TODO: Docs
# -- Global values
global:
  # -- Set additional global labels
  labels: {}
  # -- Set additional global annotations
  annotations: {}
  # -- Adds metalLB annotations to services
  addMetalLBAnnotations: false
  # -- Adds traefik annotations to services
  addTraefikAnnotations: false
  # -- Minimum nodePort value
  minNodePort: 9000

# TODO: Docs
fallbackDefaults:
  # -- Define a storageClassName that will be used for all PVCs
  # Can be overruled per PVC
  storageClass:
  # -- Default Service Protocol
  serviceProtocol: TCP
  # -- Default Service Type
  serviceType: ClusterIP
  # -- Default persistence type
  persistenceType: pvc
  # -- Default Retain PVC
  pvcRetain: false
  # -- Default PVC Size
  pvcSize: 1Gi
  # -- Default VCT Size
  vctSize: 100Gi
  # -- Default PVC/VCT Access Modes
  accessModes:
    - ReadWriteOnce

# TODO: Docs (for the imageName) convention
# -- Image values
image:
  # -- Image repository
  repository: traefik/whoami
  # -- Image tag
  tag: latest
  # -- Image pull policy
  pullPolicy: IfNotPresent

# TODO: Docs
# -- Security Context
securityContext:
  # -- Container security context for all containers
  # Can be overruled per container
  container:
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      add: []
      drop:
        - ALL
  # -- Pod security context for all pods
  # Can be overruled per pod
  pod:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: []
    sysctls: []

# TODO: Docs
containerOptions:
  # -- Resources
  # Can be overruled per container
  resources:
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 10m
      memory: 50Mi
  # -- PUID for all containers
  # Can be overruled per container
  PUID: 568
  # -- UMASK for all containers
  # Can be overruled per container
  UMASK: "002"
  NVIDIA_CAPS:
    - all

# -- Options for all pods # TODO: Docs
# Can be overruled per pod
podOptions:
  enableServiceLinks: false
  hostNetwork: false
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  dnsConfig:
    options:
      - name: ndots
        value: "2"
  hostAliases: []
  nodeSelector: {}
  tolerations: []
  schedulerName: ""
  priorityClassName: ""
  runtimeClassName: ""
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 120

# -- (docs/workload/README.md)
workload:
  main:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      # TODO: Currently implementing
      containers:
        main:
          enabled: true
          primary: true
          imageSelector: image
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              add: []
              drop:
                - ALL
          env: {}
          envList: []
          envFrom: []
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          probes:
            liveness:
              enabled: true
              type: HTTP
              port:
              path:
              httpHeaders: {}
              command: []
            readiness:
              enabled: true
              type: HTTP
              port:
              path:
              httpHeaders: {}
              command: []
            startup:
              enabled: true
              type: HTTP
              port:
              path:
              httpHeaders: {}
              command: []
      initContainers:
        init-cont-name:
          enabled: false
          type: install
          # ...containerSpec
# TODO:
portal: {}


# -- SCALE GPU (TODO: Only the resources part is left)
scaleGPU:
  - gpu:
      key: value
    # Without targetSelector, the gpu will
    # be applied to primary pod/container
    targetSelector:
      pod-name:
        - container-name

##### ⬇ Done ⬇ #####

# -- (docs/persistence/README.md)
persistence:
  shared:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /shared
    targetSelectAll: true
  varlogs:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /var/logs
    targetSelectAll: true
  tmp:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /tmp
    targetSelectAll: true
  devshm:
    enabled: false # TODO: Enable by default?
    type: emptyDir
    mountPath: /dev/shm
    targetSelectAll: true

# -- (docs/service/README.md)
service:
  main:
    enabled: true
    primary: true
    ports:
      main:
        enabled: true
        primary: true
        protocol: HTTP

# -- Timezone used everywhere applicable
TIMEZONE: UTC

# -- Injected from SCALE middleware
# Only for reference here
ixExternalInterfacesConfiguration: []
# -- Injected from SCALE middleware
# Only for reference here
ixExternalInterfacesConfigurationNames: []
# -- Injected from SCALE middleware
# Only for reference here
ixCertificates: []
# -- Injected from SCALE middleware
# Only for reference here
ixVolumes: []

# -- (docs/imagePullSecrets.md)
imagePullSecret: []

# -- (docs/configmap.md)
configmap: {}

# -- (docs/secret.md)
secret: {}

# -- (docs/serviceAccount.md)
serviceAccount: {}

# -- (docs/rbac.md)
rbac: {}

# -- (docs/volumeClaimTemplates) (StatefulSet only)
volumeClaimTemplates: {}

# -- (docs/scaleExternalInterface.md)
scaleExternalInterface: []

# -- (docs/scaleCertificate.md)
scaleCertificate: {}

# NOTES.txt TODO: Docs
notes:
  header: |
    # Welcome to SCALE
    Thank you for installing <{{ .Chart.Name }}>.
  # custom: "{{ toYaml $.Values }}"
  custom: ""
  footer: |
    # Documentation
    Documentation for this chart can be found at ...
    # Bug reports
    If you find a bug in this chart, please file an issue at ...
