name: "Charts: Release"

concurrency: helm-release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'charts/**'

jobs:
  release-charts:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      with:
        token: ${{ secrets.BOT_TOKEN }}
        ref: main
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "TrueCharts-Bot"
        git config user.email "bot@truecharts.org"

    - name: Install Helm
      uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # tag=v1
      with:
        version: v3.5.4

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@a3454e46a6f5ac4811069a381e646961dda2e1bf # tag=v1.4.0
      with:
        charts_repo_url: https://library-charts.truecharts.org
      env:
        CR_TOKEN: "${{ secrets.BOT_TOKEN }}"
        CR_SKIP_EXISTING: "true"
