name: flake8

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Set up Python 3.9
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Setup flake8 config
      run: |
        echo '[flake8]' > setup.cfg
        echo 'max-line-length = 120' >> setup.cfg
    - name: Analysing the code with flake8
      run: |
        find -name upgrade_strategy -exec sh -c "flake8  {} && exit 0 || echo $? > .exit_status" \;
        test -f .exit_status && rm .exit_status && exit 1; exit 0;
