name: flake8

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
    - name: Set up Python 3.9
      uses: actions/setup-python@152ba7c4dd6521b8e9c93f72d362ce03bf6c4f20 # v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Setup flake8 config
      run: |
        echo '[flake8]' > setup.cfg
        echo 'max-line-length = 120' >> setup.cfg
    - name: Analysing the code with flake8
      run: |
        find -name upgrade_strategy -exec sh -c "flake8  {} && exit 0 || echo $? > .exit_status" \;
        test -f .exit_status && rm .exit_status && exit 1; exit 0;
