---
name: "Metadata: Label Commenter"

on:
  workflow_dispatch:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    name: Label commenter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: main

      - uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579 # tag=v1
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
