name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@5aa4bc2e097e751b391105d89ff88c0c80519c1a # v38.1.3
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.BOT_TOKEN }}
