name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@88446f41092c9f7478c3d63199749db7a3b7e6e9 # tag=v32.202.3
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.BOT_TOKEN }}
